#include<iostream>
#include<cstdlib>
using namespace std;
int main() {

    int operarios_para_rotar [26], i, j, operarios_validar [26],;
    int rotacion [26][4];
    bool operacion_cubierta;
    for(j==0; j<4; j++){  
        
        copiar_vector_operarios(operarios_para_rotar, operarios_validar);
                       //bucle cambio de bloque
        for(i==0; i<26 ; i++){             //bucle cambio de operacion
                 
    
                 rotacion[i][j]=verificar_operacion(operarios_validar, i) 
                 
                 poner_cero_vector_copia(rotacion[i][j], operarios_validar)
                 operacion_cubiert=false;
                   


            

        }
    }



	system("pause");
	return 0;
}
